import './gb-query.tag';
import './gb-results.tag';
import './gb-record-count.tag';
import './gb-paging.tag';
import './gb-related-searches.tag';
import './gb-did-you-mean.tag';
import './gb-available-navigation.tag';
import './gb-selected-navigation.tag';
import './gb-template.tag';
