import './badge';
import * as breadcrumbs from './breadcrumbs';
// import './carousel';
// import './category-menu';
import * as collections from './collections';
import * as details from './details';
import './did-you-mean';
// import './filter';
import './icon';
import * as infiniteScroll from './infinite-scroll';
import './lazy-image';
import './link-list';
import './list';
import * as navigation from './navigation';
import * as pageSize from './page-size';
import * as paging from './paging';
import './product';
import * as query from './query';
import './raw';
import './record-count';
import './related-queries';
import './reset';
import * as results from './results';
import * as sayt from './sayt';
import './select';
import './snippet';
import * as sort from './sort';
import './submit';
import './template';
import './toggle';

export interface Config {
  breadcrumbs: breadcrumbs.Opts;
  collections: collections.Opts;
  details: details.Opts;
  infiniteScroll: infiniteScroll.Opts;
  navigation: navigation.Opts;
  pageSize: pageSize.Opts;
  paging: paging.Opts;
  query: query.Opts;
  results: results.Opts;
  sayt: sayt.Opts;
  sort: sort.Opts;
}
